name: 'ghascompliant'
description: 'ghascompliant'

inputs:
  severity:
    description: 'Severity Level'
    default: error

  action:
    description: 'Action to take upon discovery of security issues hitting threshold'
    default: break


runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "::group::Installing Dependencies"
        pushd ${{ github.action_path }}
        python3 -m pip install pipenv && python3 -m pipenv install --system
        popd
        echo "::endgroup::"
    - shell: bash
      run: |
        PYTHONPATH=${{ github.action_path }} && export PYTHONPATH=${{ github.action_path }}
        python3 -m ghascompliant --severity ${{ inputs.severity }} --action ${{ inputs.break }}
