name: 'ghascompliant'
description: 'ghascompliant'

inputs:
  severity:
    description: 'Severity Level'
    default: error

  repository:
    description: Repository owner and repo name
    default: ${{ github.repository }}

  token:
    description: GitHub Personal Access Token
    default: ${{ github.token }}
  
  ref:
    description: GitHub Ref
    default: ${{ github.ref }}

  display:
    description: 'Display alerts that violate the threshold'
    default: false

  action:
    description: 'Action to take upon discovery of security issues hitting threshold'
    default: break


runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "::group::Installing Dependencies"
        pushd ${{ github.action_path }}
        python3 -m pip install pipenv && python3 -m pipenv install --system
        popd
        echo "::endgroup::"
    - shell: bash
      run: |
        PYTHONPATH=${{ github.action_path }} && export PYTHONPATH=${{ github.action_path }}
        python3 -m ghascompliant \
          --severity ${{ inputs.severity }} \
          --action ${{ inputs.action }} \
          --display ${{ inputs.display }}
          --github-token ${{ inputs.token }} \
          --github-repository ${{ inputs.repository }} \
          --github-ref ${{ inputs.ref }}
