name: "Reporting Configuration"

# Policy Settings
policy:
  path: GeekMasher/security-queries/policies/default.yml@main
  severity: Error
  display: false


checkers:
  # Disable all dependency tooling
  dependabot: false
  dependencies: false
  licensing: false

reporting:
  issues:
    owner: GeekMasherOrg
    repository: security
